Allow optional endpoint argument
aws-controllers-k8s/runtime pull request #7
Opened 2021-03-03 05:07 UTC by nmvk

Most AWS including ElastiCache allows customers to invoke APIs using FIPS
endpoint.

https://docs.aws.amazon.com/general/latest/gr/rande.html#FIPS-endpoints

This commit introduces ability to specify endpoint URL like AWS CLI.

2021-03-03 14:19 UTC, jaypipes requested changes
I think we should take advantage of the https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/ module, including its `ResolverFunc` interface instead of manually parsing URLs in the startup of the controller.

In addition, we should be using the https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/ module's `Partition` support instead of manually setting endpoint URLs if at all possible...

2021-03-03 14:19 UTC, jaypipes commented on pkg/config/config.go
> +	flagAWSServiceEndpoint   = "aws-service-endpoint"
If this flag should be a URL (as it seems it needs to be below), this should be called `aws-endpoint-url`.

2021-03-03 14:19 UTC, jaypipes commented on pkg/config/config.go
> +	ServiceEndpoint          string
s/ServiceEndpoint/EndpointURL/g

2021-03-16 23:57 UTC, jaypipes requested changes

2021-03-16 23:57 UTC, jaypipes commented on pkg/runtime/session.go
>  	}
Add the conditional here instead.

```go
	if endpointURL != nil {
		awsCfg.Endpoint = endpointURL
	}
```

2021-03-16 23:57 UTC, jaypipes commented on pkg/config/config.go
> +		"The AWS endpoint URL the service controller will use to create its resources",
Please add some text that says this is only used to override the default behaviour of aws-sdk-go that constructs endpoint URLs automatically based on service and region.

2021-03-17 00:12 UTC, kumargauravsharma commented
As discussed the @jaypipes offline, merging this PR as the requested changes have been addressed by @nmvk

2021-03-17 00:12 UTC, kumargauravsharma approved these changes

2021-03-17 00:12 UTC, merged